"""Notification REST API Router (Phase 8.5 Milestone 1 Deliverable 6).

Exposes REST endpoints for querying notifications, unread counts, acknowledging, dismissing,
reviewing history, updating user notification preferences, and triggering test notifications.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, Field

from backend.api.dependencies import get_current_user
from backend.approval.contracts import OptimisticLockError
from backend.db.schema import User
from backend.notification.contracts import (
    ChannelType,
    DigestMode,
    InvalidNotificationStateError,
    NotificationPreference,
    PriorityLevel,
)
from backend.notification.notification_service import NotificationService

router = APIRouter(prefix="/api/notifications", tags=["Notification Engine"])

_notification_service = NotificationService()


def get_notification_service() -> NotificationService:
    return _notification_service


# Request & Response Schemas
class AckNotificationRequest(BaseModel):
    expected_version: Optional[int] = None


class DismissNotificationRequest(BaseModel):
    expected_version: Optional[int] = None


class NotificationPreferenceUpdateRequest(BaseModel):
    enabled_channels: Optional[List[str]] = Field(None, description="IN_APP, WEBSOCKET, EMAIL, SMS, PUSH")
    quiet_hours_enabled: Optional[bool] = None
    quiet_hours_start: Optional[str] = Field(None, pattern=r"^\d{2}:\d{2}$")
    quiet_hours_end: Optional[str] = Field(None, pattern=r"^\d{2}:\d{2}$")
    digest_mode: Optional[str] = Field(None, description="IMMEDIATE, HOURLY_DIGEST, DAILY_DIGEST")
    min_priority: Optional[str] = Field(None, description="CRITICAL, HIGH, MEDIUM, LOW")


class TestNotificationRequest(BaseModel):
    title: str = Field("Test Operational Alert", max_length=200)
    body: str = Field("This is a test notification generated by the Notification Engine.", max_length=1000)
    priority: str = Field("MEDIUM", description="CRITICAL, HIGH, MEDIUM, LOW")
    target_user: Optional[str] = Field(None, max_length=100)


@router.get("")
def list_notifications(
    status_filter: Optional[str] = Query(None, alias="status"),
    priority_filter: Optional[str] = Query(None, alias="priority"),
    unread_only: bool = Query(False),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    current_user: User = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
):
    """Queries notification aggregates matching filters."""
    items = service.repository.find(
        recipient_id=current_user.username,
        status=status_filter,
        priority=priority_filter,
        unread_only=unread_only,
        limit=limit,
        offset=offset,
    )
    return {
        "items": [item.to_dict() for item in items],
        "count": len(items),
        "limit": limit,
        "offset": offset,
    }


@router.get("/unread")
def get_unread_notifications(
    limit: int = Query(50, ge=1, le=200),
    current_user: User = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
):
    """Queries unread notifications and total count for the current user."""
    items = service.unread(recipient_id=current_user.username, limit=limit)
    total_unread = service.unread_count(current_user.username)
    return {
        "items": [item.to_dict() for item in items],
        "unread_count": total_unread,
    }


@router.post("/{id}/ack")
def acknowledge_notification(
    id: str,
    body: AckNotificationRequest = AckNotificationRequest(),
    current_user: User = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
):
    """Acknowledges an active notification."""
    try:
        agg = service.acknowledge(
            notification_id=id,
            actor_id=current_user.username,
            actor_role=current_user.role.value if hasattr(current_user.role, "value") else str(current_user.role),
            expected_version=body.expected_version,
        )
        return agg.to_dict()
    except OptimisticLockError as e:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(e))
    except InvalidNotificationStateError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(e))


@router.post("/{id}/dismiss")
def dismiss_notification(
    id: str,
    body: DismissNotificationRequest = DismissNotificationRequest(),
    current_user: User = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
):
    """Dismisses a notification from user view."""
    try:
        agg = service.dismiss(
            notification_id=id,
            actor_id=current_user.username,
            actor_role=current_user.role.value if hasattr(current_user.role, "value") else str(current_user.role),
            expected_version=body.expected_version,
        )
        return agg.to_dict()
    except OptimisticLockError as e:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(e))
    except InvalidNotificationStateError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(e))


@router.get("/history")
def list_notification_history(
    id: str = Query(..., description="Notification ID"),
    current_user: User = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
):
    """Queries audit history events for a notification."""
    try:
        hist = service.history(id)
        return {
            "notification_id": id,
            "events": [h.to_dict() for h in hist],
        }
    except InvalidNotificationStateError as e:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(e))


@router.get("/preferences")
def get_user_preferences(
    current_user: User = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
):
    """Gets notification preferences for current user."""
    pref = service.preferences(current_user.username)
    return pref.to_dict()


@router.put("/preferences")
def update_user_preferences(
    body: NotificationPreferenceUpdateRequest,
    current_user: User = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
):
    """Updates notification preferences for current user."""
    pref = service.preferences(current_user.username)

    if body.enabled_channels is not None:
        pref.enabled_channels = [ChannelType(c.upper()) for c in body.enabled_channels]
    if body.quiet_hours_enabled is not None:
        pref.quiet_hours_enabled = body.quiet_hours_enabled
    if body.quiet_hours_start is not None:
        pref.quiet_hours_start = body.quiet_hours_start
    if body.quiet_hours_end is not None:
        pref.quiet_hours_end = body.quiet_hours_end
    if body.digest_mode is not None:
        pref.digest_mode = DigestMode(body.digest_mode.upper())
    if body.min_priority is not None:
        pref.min_priority = PriorityLevel(body.min_priority.upper())

    updated = service.update_preferences(pref)
    return updated.to_dict()


@router.post("/test")
def trigger_test_notification(
    body: TestNotificationRequest,
    current_user: User = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
):
    """Triggers a test notification for testing multi-channel dispatch."""
    priority_enum = PriorityLevel(body.priority.upper())
    target_user = body.target_user or current_user.username

    agg = service.create_and_send(
        title=body.title,
        body=body.body,
        event_type="TEST_NOTIFICATION",
        priority=priority_enum,
        source_entity_type="TEST",
        source_entity_id="999",
        target_users=[target_user],
    )
    return agg.to_dict()
