from enum import Enum

class EventType(str, Enum):
    # Core Operations
    FIR_CREATED = "FIR_CREATED"
    FIR_UPDATED = "FIR_UPDATED"
    CRIMINAL_ARRESTED = "CRIMINAL_ARRESTED"
    HOTSPOT_UPDATED = "HOTSPOT_UPDATED"
    NEW_GRAPH_LINK = "NEW_GRAPH_LINK"

    # Investigations
    NEW_CASE = "NEW_CASE"
    CASE_UPDATED = "CASE_UPDATED"
    ENTITY_ATTACHED = "ENTITY_ATTACHED"
    ENTITY_REMOVED = "ENTITY_REMOVED"
    NOTE_ADDED = "NOTE_ADDED"

    # Intelligence
    INTELLIGENCE_DISCOVERED = "INTELLIGENCE_DISCOVERED"
    RISK_SCORE_CHANGED = "RISK_SCORE_CHANGED"
    RECOMMENDATION_GENERATED = "RECOMMENDATION_GENERATED"

    # Phase 8.1: Task Engine
    TASK_CREATED = "TASK_CREATED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_SKIPPED = "TASK_SKIPPED"
    TASK_UNBLOCKED = "TASK_UNBLOCKED"
    TASK_SLA_WARNING = "TASK_SLA_WARNING"
    TASK_SLA_BREACHED = "TASK_SLA_BREACHED"
    TASK_TEMPLATE_INSTANTIATED = "TASK_TEMPLATE_INSTANTIATED"

    # Phase 8.2 Milestone 4: Assignment Service Events
    ASSIGNMENT_RECOMMENDED = "ASSIGNMENT_RECOMMENDED"
    ASSIGNMENT_VALIDATED = "ASSIGNMENT_VALIDATED"
    ASSIGNMENT_CREATED = "ASSIGNMENT_CREATED"
    ASSIGNMENT_REASSIGNED = "ASSIGNMENT_REASSIGNED"
    ASSIGNMENT_FAILED = "ASSIGNMENT_FAILED"

    # Phase 8.2 Milestone 5: Governance & Approval Events
    ASSIGNMENT_ACCEPTED = "ASSIGNMENT_ACCEPTED"
    ASSIGNMENT_OVERRIDDEN = "ASSIGNMENT_OVERRIDDEN"
    ASSIGNMENT_REJECTED = "ASSIGNMENT_REJECTED"
    ASSIGNMENT_DEFERRED = "ASSIGNMENT_DEFERRED"
    ASSIGNMENT_ESCALATED = "ASSIGNMENT_ESCALATED"
    ASSIGNMENT_APPROVED = "ASSIGNMENT_APPROVED"
    ASSIGNMENT_POLICY_WARNING = "ASSIGNMENT_POLICY_WARNING"



