from enum import Enum

class EventType(str, Enum):
    # Core Operations
    FIR_CREATED = "FIR_CREATED"
    FIR_UPDATED = "FIR_UPDATED"
    CRIMINAL_ARRESTED = "CRIMINAL_ARRESTED"
    HOTSPOT_UPDATED = "HOTSPOT_UPDATED"
    NEW_GRAPH_LINK = "NEW_GRAPH_LINK"

    # Investigations
    NEW_CASE = "NEW_CASE"
    CASE_UPDATED = "CASE_UPDATED"
    ENTITY_ATTACHED = "ENTITY_ATTACHED"
    ENTITY_REMOVED = "ENTITY_REMOVED"
    NOTE_ADDED = "NOTE_ADDED"

    # Intelligence
    INTELLIGENCE_DISCOVERED = "INTELLIGENCE_DISCOVERED"
    RISK_SCORE_CHANGED = "RISK_SCORE_CHANGED"
    RECOMMENDATION_GENERATED = "RECOMMENDATION_GENERATED"

    # Phase 8.1: Task Engine
    TASK_CREATED = "TASK_CREATED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_SKIPPED = "TASK_SKIPPED"
    TASK_UNBLOCKED = "TASK_UNBLOCKED"
    TASK_SLA_WARNING = "TASK_SLA_WARNING"
    TASK_SLA_BREACHED = "TASK_SLA_BREACHED"
    TASK_TEMPLATE_INSTANTIATED = "TASK_TEMPLATE_INSTANTIATED"

    # Phase 8.2 Milestone 4: Assignment Service Events
    ASSIGNMENT_RECOMMENDED = "ASSIGNMENT_RECOMMENDED"
    ASSIGNMENT_VALIDATED = "ASSIGNMENT_VALIDATED"
    ASSIGNMENT_CREATED = "ASSIGNMENT_CREATED"
    ASSIGNMENT_REASSIGNED = "ASSIGNMENT_REASSIGNED"
    ASSIGNMENT_FAILED = "ASSIGNMENT_FAILED"

    # Phase 8.2 Milestone 5: Governance & Approval Events
    ASSIGNMENT_ACCEPTED = "ASSIGNMENT_ACCEPTED"
    ASSIGNMENT_OVERRIDDEN = "ASSIGNMENT_OVERRIDDEN"
    ASSIGNMENT_REJECTED = "ASSIGNMENT_REJECTED"
    ASSIGNMENT_DEFERRED = "ASSIGNMENT_DEFERRED"
    ASSIGNMENT_ESCALATED = "ASSIGNMENT_ESCALATED"
    ASSIGNMENT_APPROVED = "ASSIGNMENT_APPROVED"
    ASSIGNMENT_POLICY_WARNING = "ASSIGNMENT_POLICY_WARNING"

    # Phase 8.4: Approval System Events
    APPROVAL_SUBMITTED = "APPROVAL_SUBMITTED"
    APPROVAL_ASSIGNED = "APPROVAL_ASSIGNED"
    APPROVAL_STAGE_CHANGED = "APPROVAL_STAGE_CHANGED"
    APPROVAL_APPROVED = "APPROVAL_APPROVED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_RETURNED = "APPROVAL_RETURNED"
    APPROVAL_ESCALATED = "APPROVAL_ESCALATED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    APPROVAL_CANCELLED = "APPROVAL_CANCELLED"

    # Phase 8.4 Milestone 2: Escalation & SLA Governance Events
    APPROVAL_ESCALATION_CREATED = "APPROVAL_ESCALATION_CREATED"
    APPROVAL_ESCALATION_ACKNOWLEDGED = "APPROVAL_ESCALATION_ACKNOWLEDGED"
    APPROVAL_ESCALATION_RESOLVED = "APPROVAL_ESCALATION_RESOLVED"
    APPROVAL_DELEGATED = "APPROVAL_DELEGATED"
    APPROVAL_REASSIGNED = "APPROVAL_REASSIGNED"
    SLA_WARNING = "SLA_WARNING"
    SLA_BREACHED = "SLA_BREACHED"
    REMINDER_SENT = "REMINDER_SENT"

    # Phase 8.5 Milestone 1: Notification Engine Events
    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
    NOTIFICATION_DISPATCHED = "NOTIFICATION_DISPATCHED"
    NOTIFICATION_DELIVERED = "NOTIFICATION_DELIVERED"
    NOTIFICATION_ACKNOWLEDGED = "NOTIFICATION_ACKNOWLEDGED"
    NOTIFICATION_DISMISSED = "NOTIFICATION_DISMISSED"
    NOTIFICATION_FAILED = "NOTIFICATION_FAILED"
    NOTIFICATION_EXPIRED = "NOTIFICATION_EXPIRED"

    # Phase 8.5 Milestone 2: Notification Hub & Communication Events
    NOTIFICATION_DIGEST_CREATED = "NOTIFICATION_DIGEST_CREATED"
    NOTIFICATION_DIGEST_SENT = "NOTIFICATION_DIGEST_SENT"
    NOTIFICATION_BATCH_CREATED = "NOTIFICATION_BATCH_CREATED"
    NOTIFICATION_BATCH_SENT = "NOTIFICATION_BATCH_SENT"
    NOTIFICATION_REMINDER_CREATED = "NOTIFICATION_REMINDER_CREATED"
    NOTIFICATION_REMINDER_SENT = "NOTIFICATION_REMINDER_SENT"
    NOTIFICATION_ARCHIVED = "NOTIFICATION_ARCHIVED"
    NOTIFICATION_PINNED = "NOTIFICATION_PINNED"
    NOTIFICATION_STARRED = "NOTIFICATION_STARRED"
    NOTIFICATION_THREAD_UPDATED = "NOTIFICATION_THREAD_UPDATED"
    NOTIFICATION_INBOX_UPDATED = "NOTIFICATION_INBOX_UPDATED"



