"""
NEXUS Simulator — Simulation Engine
Day-by-day simulation loop that:
  - Advances calendar context
  - Determines which criminals are active each day
  - Generates crime events proportional to day risk context
  - Updates career states
  - Produces an ordered list of raw crime events
"""
from __future__ import annotations
import numpy as np
import logging
from datetime import date, timedelta
from typing import List, Dict, Callable, Optional

from simulator.config.settings import Settings
from simulator.timeline.calendar import KarnatakaCalendar, DayContext
from simulator.criminals.profiles import CriminalProfile
from simulator.criminals.career import CareerManager
from simulator.geography.karnataka import Station
from simulator.geography.coordinates import CoordinateSampler

logger = logging.getLogger(__name__)


class SimulationEngine:
    """
    Orchestrates the day-by-day simulation.
    Crime events are generated by calling registered crime generators.
    """

    def __init__(
        self,
        settings: Settings,
        rng: np.random.Generator,
        criminals: List[CriminalProfile],
        stations: List[Station],
        career_manager: CareerManager,
        coord_sampler: CoordinateSampler,
    ) -> None:
        self.settings = settings
        self.rng = rng
        self.criminals = criminals
        self.stations = stations
        self.career_manager = career_manager
        self.coord_sampler = coord_sampler
        self.calendar = KarnatakaCalendar()
        
        from simulator.timeline.campaigns import CampaignManager
        self.campaign_manager = CampaignManager(rng)

        # Crime generator callbacks: fn(day_ctx, active_criminals, rng, coord_sampler) → List[raw_event]
        self._crime_generators: List[Callable] = []

        # Results
        self.raw_crime_events: List[dict] = []
        self.simulation_days: List[DayContext] = []
        
        # Dynamic Police Response (Patrol Surges)
        self.district_crime_history: Dict[str, List[int]] = {s.district_id: [] for s in stations}
        self.active_surges: Dict[str, int] = {} # district_id -> days_remaining

    def register_crime_generator(self, fn: Callable) -> None:
        """Register a callback that generates crimes for a given day."""
        self._crime_generators.append(fn)

    def run(self, target_fir_count: int) -> None:
        """
        Run the simulation until target_fir_count crimes have been generated.
        Uses the configured start date and advances day by day.
        """
        start = date(
            self.settings.sim_start_year,
            self.settings.sim_start_month,
            self.settings.sim_start_day,
        )

        current_date = start
        crimes_generated = 0
        day_count = 0
        max_days = 365 * 10  # Safety cap: 10 years

        # Build criminal lookup
        criminal_map: Dict[str, CriminalProfile] = {c.criminal_id: c for c in self.criminals}

        logger.info(f"Simulation start: {start} | Target FIRs: {target_fir_count}")

        while crimes_generated < target_fir_count and day_count < max_days:
            day_ctx = self.calendar.get_day_context(current_date)
            self.simulation_days.append(day_ctx)

            # Advance career states
            self.career_manager.tick(current_date, self.criminals, self.stations)

            # Get active criminals for today
            active_today = [
                c for c in self.criminals
                if self.career_manager.can_offend_today(c.criminal_id, current_date)
            ]

            # How many crimes to generate today?
            # Base: target_fir_count / patrol_days, scaled by overall risk
            base_crimes_per_day = target_fir_count / max(self.settings.patrol_days, 365)
            today_crimes = int(base_crimes_per_day * day_ctx.overall_risk)
            today_crimes = max(1, today_crimes)

            # Generate crimes via registered generators
            day_events: List[dict] = []
            executing_campaigns = self.campaign_manager.tick(current_date, active_today, self.stations)
            remaining = today_crimes
            for gen in self._crime_generators:
                if remaining <= 0:
                    break
                events = gen(
                    day_ctx=day_ctx,
                    active_criminals=active_today,
                    rng=self.rng,
                    coord_sampler=self.coord_sampler,
                    stations=self.stations,
                    count=remaining,
                    campaigns=executing_campaigns,
                    active_surges=self.active_surges
                )
                day_events.extend(events)
                remaining -= len(events)

            self.raw_crime_events.extend(day_events)
            crimes_generated += len(day_events)
            
            # Update Police Response Feedback Loop
            # 1. Tally today's crimes per district
            today_tally = {d: 0 for d in self.district_crime_history}
            for e in day_events:
                # Assuming CrimeEvent has district_id property, but here it's an object
                if hasattr(e, 'district_id'):
                    d = e.district_id
                    if d in today_tally:
                        today_tally[d] += 1
            
            # 2. Update history and check surges
            for d, history in self.district_crime_history.items():
                history.append(today_tally[d])
                if len(history) > 7:
                    history.pop(0)
                    
                # If last 7 days > 15 crimes (example threshold), trigger surge
                if sum(history) > 15:
                    self.active_surges[d] = 5 # 5 day surge
                    
                # Decrement active surges
                if d in self.active_surges:
                    self.active_surges[d] -= 1
                    if self.active_surges[d] <= 0:
                        del self.active_surges[d]
                        # Reset history so we don't immediately trigger again
                        self.district_crime_history[d] = [0]*7

            if day_count % 30 == 0:
                logger.info(
                    f"Day {day_count:4d} | {current_date} | "
                    f"Crimes today: {len(day_events):3d} | "
                    f"Total: {crimes_generated:6d}/{target_fir_count}"
                )

            current_date += timedelta(days=1)
            day_count += 1

        logger.info(f"Simulation complete. Days: {day_count} | Crimes: {crimes_generated}")

    @property
    def date_range(self):
        if self.simulation_days:
            return self.simulation_days[0].date, self.simulation_days[-1].date
        return None, None
